import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import TaskList from "@tiptap/extension-task-list";
import TaskItem from "@tiptap/extension-task-item";
import Collaboration from "@tiptap/extension-collaboration";
import * as Y from "yjs";
import { WebsocketProvider } from "y-websocket";
import "y-indexeddb";
import "./style.css";
type Note = { id: string; title: string; excerpt: string; updated_at: string; deleted_at: string | null };
const api = async <T,>(path: string, init: RequestInit = {}): Promise<T> => { const token = localStorage.getItem("token"); const res = await fetch(`/api${path}`, { ...init, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init.headers } }); if (!res.ok) throw new Error((await res.json()).error ?? "Request failed"); return res.status === 204 ? (undefined as T) : res.json(); };
function Login({ onLogin }: { onLogin: () => void }): React.ReactElement { const [register, setRegister] = useState(false), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState(""); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { const result = await api<{ token: string }>(register ? "/auth/register" : "/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); localStorage.setItem("token", result.token); onLogin(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in"); } }; return <main className="login"><form onSubmit={submit}><h1>Syncbook</h1><input aria-label="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" required /><input aria-label="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" minLength={8} required /><button>{register ? "Create account" : "Log in"}</button>{error && <p className="error">{error}</p>}<button type="button" className="link" onClick={() => setRegister(!register)}>{register ? "Already registered?" : "Create an account"}</button></form></main>; }
function Editor({ note, token, onChanged }: { note: Note; token: string; onChanged: () => void }): React.ReactElement { const [status, setStatus] = useState("connecting"); const ydoc = useMemo(() => new Y.Doc(), [note.id]); const provider = useMemo(() => new WebsocketProvider(`${location.protocol === "https:" ? "wss" : "ws"}://${location.host}/ws`, note.id, ydoc, { params: { token } }), [note.id, token, ydoc]); const editor = useEditor({ extensions: [StarterKit, TaskList, TaskItem.configure({ nested: true }), Collaboration.configure({ document: ydoc })], editorProps: { attributes: { class: "editor" } } }); useEffect(() => { provider.on("status", ({ status: s }: { status: string }) => setStatus(s === "connected" ? "saving" : "offline")); const observer = () => onChanged(); ydoc.on("update", observer); return () => { ydoc.off("update", observer); provider.destroy(); editor?.destroy(); }; }, [provider, ydoc, editor, onChanged]); return <section className="editor-pane"><div className="editor-header"><strong>{note.title || "Untitled note"}</strong><span>{status}</span></div><EditorContent editor={editor} /></section>; }
function App(): React.ReactElement { const [loggedIn, setLoggedIn] = useState(Boolean(localStorage.getItem("token"))); const [notes, setNotes] = useState<Note[]>([]), [selected, setSelected] = useState<Note | null>(null), [search, setSearch] = useState(""); const load = async () => { const list = await api<Note[]>("/notes"); setNotes(list); if (!selected && list[0]) setSelected(list[0]); }; useEffect(() => { if (loggedIn) void load(); }, [loggedIn]); if (!loggedIn) return <Login onLogin={() => setLoggedIn(true)} />; const visible = notes.filter((n) => `${n.title} ${n.excerpt}`.toLowerCase().includes(search.toLowerCase())); const create = async () => { const note = await api<Note>("/notes", { method: "POST" }); setNotes([note, ...notes]); setSelected(note); }; return <main className="app"><aside><header><h1>Syncbook</h1><button onClick={() => void create()}>＋</button></header><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search notes" />{visible.map((n) => <button className={`note ${selected?.id === n.id ? "active" : ""}`} key={n.id} onClick={() => setSelected(n)}><b>{n.title || "Untitled note"}</b><small>{n.excerpt || "Empty note"}</small><time>{new Date(n.updated_at).toLocaleString()}</time></button>)}</aside>{selected ? <Editor note={selected} token={localStorage.getItem("token") ?? ""} onChanged={() => void load()} /> : <div className="empty">Create a note to get started.</div>}</main>; }
createRoot(document.getElementById("root")!).render(<App />);
